### ISSUE TITLE
Bridge UI json error  

### ISSUE THREAD

**Issue by JohannEid** [poanetwork/tokenbridge#124]
When trying to do a transfer of tokens from Ropsten to Thunder Testnet I get the following :

"Returned error: invalid argument 0: json cannot unmarshal non-strong into Go value of type *hexutil.Big"

My .env file : 

REACT_APP_HOME_BRIDGE_ADDRESS=0xD9a3628ca04E95D493CaeAF91dDa79e84E387F8d
REACT_APP_FOREIGN_BRIDGE_ADDRESS=0x7FDF1F5a9425472D2528f8e8B30856B5ba43B49f

REACT_APP_HOME_HTTP_PARITY_URL=https://testnet-rpc.thundercore.com/
REACT_APP_FOREIGN_HTTP_PARITY_URL=https://ropsten.infura.io

**Comment by patitonar** [comment]
Hi @JohannEid ! Can you specify in which exact step do you get this error? Can you also share the logs from console?

I run the bridge-ui with those parameters, it looks like https://testnet-rpc.thundercore.com/ does not support `eth_chainId` call which is used in the app.

To know if the reported error is related to this, for your case, let's try to use `networkId` instead of the `chainId`. Can you try replacing `web3.eth.getChainId()` with `web3.eth.net.getId()` on lines `83` and `101` of `web3.js` file?

https://github.com/poanetwork/tokenbridge/blob/47a0a7c0f5e902add73250b41b6cd65c65f1bbb7/ui/src/stores/utils/web3.js#L82-L108

**Comment by JohannEid** [comment]
Hey @patitonar ,

Replacing web3.eth.getChainId() with web3.eth.net.getId() on lines 83 and 101 of web3.js file worked.

Thank you very much for solving this.

**Comment by PeterTheOne** [comment]
I think it is not that the RPC doesn't support `eth_chainId`, it is more like the web3 version doesn't yet have the `web3.eth.getChainId()` method. Upgrade of web3 to at least version 1.2.2 helps, see PR https://github.com/poanetwork/tokenbridge/pull/494 .
