### ISSUE TITLE
Consistent variable naming across components and deployment

### ISSUE THREAD

**Issue by rzadp** [poanetwork/tokenbridge#127]
https://github.com/poanetwork/tokenbridge/pull/126#discussion_r300493636

We should have consistent naming across variables used in Oracle and variables used in Oracle deployment.
Same for UI and Monitor.

We should have clear instructions on which variables are required when deploying standalone Oracle, standalone UI and Oracle+UI

**Comment by akolotov** [comment]
Here is my new suggestion for naming of parameters in the components `.env` files and the deployment configuration (located in `group_vars`):

First of all all three components have common parameters:
```shell
COMMON_HOME_RPC_URL=https://kovan.infura.io/mew
COMMON_FOREIGN_RPC_URL=https://kovan.infura.io/mew
COMMON_HOME_BRIDGE_ADDRESS=0x86b621b839Ff86Bb59fA57015b02318f9a870d80
COMMON_FOREIGN_BRIDGE_ADDRESS=0x8dDCa2eB86D22FcB93342753515986e258A90169

COMMON_HOME_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
COMMON_HOME_GAS_PRICE_SPEED_TYPE=standard
COMMON_HOME_GAS_PRICE_FALLBACK=1000000000
COMMON_HOME_GAS_PRICE_FACTOR=1

COMMON_FOREIGN_GAS_PRICE_ORACLE_URL=https://gasprice.poa.network/
COMMON_FOREIGN_GAS_PRICE_SPEED_TYPE=standard
COMMON_FOREIGN_GAS_PRICE_FALLBACK=1000000000
COMMON_FOREIGN_GAS_PRICE_FACTOR=1
```
_Please note that `ERC20_TOKEN_ADDRESS` is not need to be specified any more since this information could be [extracted from the blockchain](https://github.com/poanetwork/tokenbridge/search?q=ERC20_TOKEN_ADDRESS&unscoped_q=ERC20_TOKEN_ADDRESS)._

The configuration parameters specific for the oracle are:
```shell
ORACLE_BRIDGE_MODE=ERC_TO_ERC
ORACLE_ALLOW_HTTP_FOR_RPC=no
ORCALE_HOME_RPC_POLLING_INTERVAL=5000
ORACLE_FOREIGN_RPC_POLLING_INTERVAL=1000

ORACLE_HOME_GAS_PRICE_UPDATE_INTERVAL=600000
ORACLE_FOREIGN_GAS_PRICE_UPDATE_INTERVAL=600000

ORACLE_QUEUE_URL=amqp://rabbit
ORACLE_REDIS_URL=redis://redis

ORACLE_HOME_START_BLOCK=
ORACLE_FOREIGN_START_BLOCK=

ORACLE_LOG_LEVEL=debug
ORACLE_MAX_PROCESSING_TIME=20000
```

The corresponding parameters specific for the UI:
```shell
UI_APP_TITLE=TokenBridge UI app - %c
UI_APP_DESCRIPTION=The POA cross-chain bridge serves as a method of transferring POA native tokens from the POA Network to the Ethereum network in a quick and cost-efficient manner.

UI_NATIVE_TOKEN_DISPLAY_NAME=POA

UI_HOME_NETWORK_DISPLAY_NAME=POA Sokol
UI_FOREIGN_NETWORK_DISPLAY_NAME=Kovan

UI_HOME_WITHOUT_EVENTS=false
UI_FOREIGN_WITHOUT_EVENTS=false

UI_HOME_EXPLORER_TX_TEMPLATE=https://blockscout.com/poa/sokol/tx/%s
UI_FOREIGN_EXPLORER_TX_TEMPLATE=https://blockscout.com/eth/kovan/tx/%s
UI_HOME_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/poa/sokol/address/%s
UI_FOREIGN_EXPLORER_ADDRESS_TEMPLATE=https://blockscout.com/eth/kovan/address/%s

UI_HOME_GAS_PRICE_UPDATE_INTERVAL=15000
UI_FOREIGN_GAS_PRICE_UPDATE_INTERVAL=15000

UI_PORT=3000

UI_APP_STYLES=classic
```

The value of `*_GAS_PRICE_UPDATE_INTERVAL` could differ from the corresponding parameters of the oracle since update interval could differ in the oracle and in the UI.

And the monitor has its own set of the unique parameters:
```
MONITOR_HOME_START_BLOCK=0
MONITOR_FOREIGN_START_BLOCK=0

MONITOR_VALIDATOR_HOME_TX_LIMIT=300000
MONITOR_VALIDATOR_FOREIGN_TX_LIMIT=300000

MONITOR_TX_NUMBER_THRESHOLD=100
MONITOR_PORT=3003
```

The values of parameters `*_START_BLOCK` could differ too in the oracle and in the monitor. The oracle's meaning for them is the block where validator was added to the validator set whereas the monitor should use them to track all the transactions starting from the block where the bridge contracts were deployed. Later, we need to add an issue to modify this behavior as so the monitor get these values from (`deployedAtBlock()`](https://github.com/poanetwork/poa-bridge-contracts/blob/37793f5bca7c942f6787dc6bcea7e5a50cee8e73/contracts/upgradeable_contracts/Initializable.sol#L17).

So, if this naming is OK, we need to update all components and their configuration with new parameters names also as the deployment playbooks code and examples of configurations.

**Comment by rzadp** [comment]
1. There seems to be missing parameter `VALIDATOR_ADDRESS_PRIVATE_KEY`. I will name it `ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY`, unless it was left out on purpose?
2. It seems like good opportunity to rename `COMMON_HOME_GAS_PRICE_ORACLE_URL` to `COMMON_HOME_GAS_PRICE_SUPPLIER_URL` and close https://github.com/poanetwork/tokenbridge/issues/180

**Comment by akolotov** [comment]
1. Yes, that's correct. Thanks! I missed it since it does not required to be specified in `group_vars`.
2. Yes, let's rename it as you suggested.

**Comment by rzadp** [comment]
In addition to variables listed in https://github.com/poanetwork/tokenbridge/issues/127#issuecomment-526509190 there are:
```
ERC20_TOKEN_ADDRESS (this will be removed in a separate PR)

(specified in hosts.yml)
ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY
ORACLE_VALIDATOR_ADDRESS
```

**Comment by rzadp** [comment]
### UI variable problem

Turns out that `react-app-rewired`, which is used in `UI`, automatically picks up variables starting with `REACT_APP_`, and does not recognize other variables. This is on [purpose](https://create-react-app.dev/docs/adding-custom-environment-variables).

So our `UI_` variables can simply be renamed to `REACT_APP_`.
The exception to this is `PORT` variable, which cannot be consistently called `REACT_APP_PORT`.

But the main problem are with `COMMON_` variables. They are not picked up by `UI`.

#### Solution to deployment

The solution to deployment, is to just add the prefix to `COMMON_` variables, like so:
```
REACT_APP_COMMON_FOREIGN_RPC_URL={{ COMMON_FOREIGN_RPC_URL }}
```

This works and solves the problem

#### Solution to local

The UI application can be run locally by using docker, and by using `yarn start`.
The `COMMON_` variables can be prefixed using `env:` in `docker-compose.yml`.
If using `yarn start`, we could utilise some npm script that would modify the file and prefix the variables if needed.

But this seems too complicated. My proposal is to have prefixed `COMMON_` vars in `ui/.env.example`, and specify this in the documentation

@akolotov @patitonar Do you have any other ideas?

**Comment by akolotov** [comment]
@rzadp thanks for analysis.

I have looked through the code and found the following:

https://github.com/poanetwork/tokenbridge/blob/6dc4fc6acddb48c1bc108d3d336742eb27b63dea/ui/package.json#L36

https://github.com/poanetwork/tokenbridge/blob/6dc4fc6acddb48c1bc108d3d336742eb27b63dea/ui/scripts/selectTheme.js#L11

https://github.com/poanetwork/tokenbridge/blob/6dc4fc6acddb48c1bc108d3d336742eb27b63dea/ui/package.json#L49

These are parts where we "customize" the application appearance or logic before running. So, if we chose to use a pre-processing script to apply an interim input stream template to artificially generate `.env` file or (that could be even better) a JSON file, we will not break lots of our current design patterns. 

This interim input stream could be a file with environment variables. But another approach is also considerable.

I would prefer to have clear and self-explanatory configuration parameters (without questionable `REACT_APP_...`) and some automated pre-processing if this help users to apprehend the TokenBridge toolkit as a whole.
