### ISSUE TITLE
"legacy access request rate exceeded" message when monitor is run for WETC bridge

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge#150]
During the work for #148, the monitor was tested for WETC bridge and the following message appears: `legacy access request rate exceeded`.

<img width="869" alt="Screenshot 2019-07-12 at 11 21 07" src="https://user-images.githubusercontent.com/12039224/61117915-e3c70a00-a497-11e9-8c2e-7fa2762914ca.png">

**Comment by rzadp** [comment]
@akolotov I think you meant https://github.com/poanetwork/tokenbridge/pull/143 ?

**Comment by akolotov** [comment]
> @akolotov I think you meant #143 ?

yes, thanks

**Comment by akolotov** [comment]
@patitonar I am assigning this issue to you. We need to understand what caused this issue and if it could affect other bridges.

**Comment by patitonar** [comment]
The issue seems to be related to old Infura API, when using Infura we should use the new `v3` endpoints. Correct me if I'm wrong but for the monitor I believe we are using private nodes for mainnet, so that's probably why `https://mainnet.infura.io/` was defined as placeholder on `wetc.yml` file. On UI all of our bridges are using `v3` Infura endpoints. 
So I don't think there is a fix needed for this.

Here is more information about the error message `legacy access request rate exceeded`:
- https://community.infura.io/t/legacy-key-deprecation/443
- https://community.infura.io/t/legacy-access-request-rate-exceeded/490

**Comment by akolotov** [comment]
Thanks for investigation. So, the issue is due to improper configuration. Closing it
