### ISSUE TITLE
possibly error on processCollectedSignatures

### ISSUE THREAD

**Issue by LiorRabin** [poanetwork/tokenbridge#227]
Hi,

I think that there's an error on `processCollectedSignatures` events.
See https://github.com/poanetwork/tokenbridge/blob/9884b4b424fd51b243a805f356c94238a7a1ab3a/oracle/src/events/processCollectedSignatures/index.js#L26

Shouldn't the `validatorContract` be taken from the `homeBridge`? 

In https://github.com/poanetwork/tokenbridge/blob/master/oracle/src/events/processCollectedSignatures/estimateGas.js there are checks for `requiredSignatures` and if all signers are in fact validators - and all the signature happen on the home network right? 

See https://github.com/poanetwork/tokenbridge-contracts/blob/ec8feef1102640e95e736aa15166caed7fa84d17/contracts/upgradeable_contracts/BasicHomeBridge.sol#L56

Thanks

**Comment by akolotov** [comment]
Hi @LiorRabin, in fact the validator contract is used in `estimateGas` to find out the reason why the call of [`executeSignatures` on the Foreign bridge contract](https://github.com/poanetwork/tokenbridge/blob/9884b4b424fd51b243a805f356c94238a7a1ab3a/oracle/src/events/processCollectedSignatures/estimateGas.js#L14) could fail. Since `executeSignatures` [operates with data from the validators contract on the Foreign side](https://github.com/poanetwork/tokenbridge-contracts/blob/86b35f8382d5cb98e5738128a0c1a3718c471c72/contracts/upgradeable_contracts/BasicForeignBridge.sol#L17), the corresponding worker examines the data on the foreign side as well.

If you think that I missed something in my logic please let me know.

**Comment by LiorRabin** [comment]
Hi @akolotov, yeah I now understand it.
My mistake - closing the issue.
Thanks
