### ISSUE TITLE
authorityResponsibleForRelay issue

### ISSUE THREAD

**Issue by LiorRabin** [poanetwork/tokenbridge#266]
Hello,
I have an issue with `authorityResponsibleForRelay` check in the `processCollectedSignatures` event watcher.
What happens if that specific validator is down indefinitely? 
How can the `exectureSignatures` function be called?
Is there an option to make some kind of queue there - give the `authorityResponsibleForRelay` some time to process and if not processed, move over to the next validator?

**Comment by akolotov** [comment]
@LiorRabin as you can see in the Foreign Bridge contract: https://github.com/poanetwork/tokenbridge-contracts/blob/e2d3cdabee6d4579dd6a5e1949ee98c79cd1cbe6/contracts/upgradeable_contracts/BasicForeignBridge.sol#L18-L34, there are no limitations to call the `executeSignatures` method by anyone. It was intentionally designed as so if an oracle responsible for relaying signatures fails by some reason any account could collect signatures from the Home bridge contract and send them to the Foreign side. This action does not require any consensus since the signatures are very hard to forge.

We even have [an issue](https://github.com/poanetwork/bridge-ui/issues/156) against the TokenBridge UI functionality to allow the end user to submit signatures instead of the validator's oracle.

**Comment by LiorRabin** [comment]
Thanks @akolotov. I know there are no limitations to call `executeSignatures` just thought to ask if there's any intention to build a fallback on the oracle itself for this specific case.

**Comment by akolotov** [comment]
@LiorRabin so far we had no such intention the reasons are:
* we could detect that the signatures relay operation is stuck in the monitor and re-send signatures from any account
* we have the open issue to implement functionality allowing the user to re-send collected signatures if they need to speed up the process

Otherwise we need to invent a way to build communication channels between oracles that will be used to identify oracles that out-of-service and duplicate the actions. But it was assumed that every oracle does not require any information about other bridge participants: neither the validators number nor their addresses.

**Comment by LiorRabin** [comment]
Got it, thanks for the info
