### ISSUE TITLE
Add bridge contracts as git submodule

### ISSUE THREAD

**Issue by patitonar** [poanetwork/tokenbridge#33]
Add `poa-bridge-contracts` (branch `refactor_v1`) repository as a git submodule and use compiled contracts instead of contracts on `abis` directory

**Comment by akolotov** [comment]
Correct. I specified in #21 a list of work that needs to be done there as per the approach you are suggesting to follow: small set of changes for one issue.

**Comment by akolotov** [comment]
Let's consider this issue to introduce compilation of the contracts in the process of installing dependencies.
- [ ] use ABIs of installed contracts in the oracle instead of pre-compiled ABIs.
- [ ] use ABIs of installed contracts in the UI instead of pre-compiled ABIs.
- [ ] use ABIs of installed contracts in the monitor instead of pre-compiled ABIs.

The most actual version of contracts should be used at the moment when this issue is assigned for implementation.

**Comment by rzadp** [comment]
This was done in #21
