### ISSUE TITLE
Unclear error message if gas price oracle is not available 

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge#84]
During operations with POA bridge it was found that the following unclear message appear if the gas price was not available:

![image](https://user-images.githubusercontent.com/20793260/58738498-b570fc00-840e-11e9-9212-152c873d7cad.png)

To understand that the issue is related to the gas price oracle it is necessary to look at the development console logs:

![image](https://user-images.githubusercontent.com/20793260/58738520-c588db80-840e-11e9-9817-0a6ad533d8e8.png)

Consider to provide more clear error description to the user.

**Comment by patitonar** [comment]
This issue only affects version `1` of bridge UI, in current version if call to gas price oracle fails it doesn't display any error to the user because we can still use the fallback values provided by `.env` file.

Added a PR to improve error message on V1 https://github.com/poanetwork/bridge-ui/pull/221

**Comment by akolotov** [comment]
It was addressed in a special branch for v1.x token bridge UI in the standalone repo.
