### ISSUE TITLE
Update the tests to NOT use .env and hardcode HOME_RPC_URL and FOREIGN_RPC_URL

### ISSUE THREAD

**Issue by pertsev** [poanetwork/tokenbridge#90]
This couple of tests is constantly failing 
https://github.com/poanetwork/token-bridge/blob/adb29317b070f620ee5749b54272f822b6446e3d/test/gasPrice.test.js#L116-L140

Environment:
node 10
yarn 1.16.0

![image](https://user-images.githubusercontent.com/11399003/59083954-310af700-88ae-11e9-9b04-ef6791493961.png)

**Comment by akolotov** [comment]
Please check on the monorepo. CircleCI reports about successful runs of all tests: [tests on the latest master commit](https://circleci.com/gh/poanetwork/tokenbridge/1335)

**Comment by pertsev** [comment]
@akolotov The same story on `yarn test` in monorepo 

![image](https://user-images.githubusercontent.com/11399003/59084922-cb206e80-88b1-11e9-9552-233603c6cd9a.png)

**Comment by rzadp** [comment]
@pertsev Please try the following:
```
cd tokenbridge/oracle
mv .env .env.bak
echo -e "HOME_RPC_URL=http://example.com\nFOREIGN_RPC_URL=http://example.com\n" > .env
yarn test
```

---

@akolotov The issue is that the oracle tests require specific set of env vars. They're set up on CI following the setup I saw on `.travis.yml`:
![Screenshot 2019-06-07 at 09 06 58](https://user-images.githubusercontent.com/12039224/59086952-9f2dd900-8903-11e9-9957-b0751858202a.png)

Apparently they fail if there is more vars (specifically `HOME_GAS_PRICE_UPDATE_INTERVAL` and `FOREIGN_GAS_PRICE_UPDATE_INTERVAL`), which are introduced when doing `cp .env.example .env`

So I figure that this issue should be renamed into either:
- Update the documentation
- or, Update the tests to NOT use .env and hardcode `HOME_RPC_URL` and `FOREIGN_RPC_URL` ?

**Comment by akolotov** [comment]
@rzadp thanks for the investigation. I would vote for the second approach.

are you going to address it or I could ask Gerardo (@patitonar)

**Comment by rzadp** [comment]
I will try and fix it with the second approach.

**Comment by akolotov** [comment]
@rzadp thanks
