### ISSUE TITLE
logs are being flooded with messages from the oracle sender in case of error

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge#94]
If by some reason the oracle sender cannot send a transaction it produces dozens of messages: https://gist.github.com/akolotov/465c35bd0656e0bb5ec74afceefe8542. It becomes very hard to investigate the issue since the logs are flooded with the same messages.

It is necessary to investigate why re-tries to send the message happens too fast and suggest a way to address the issue with logs.

**Comment by patitonar** [comment]
The sender is subscribed to a rabbitmq queue to take jobs one at the time. When the watcher get some events on a block, it creates an array with those events and push one job (containing the array) to the queue. When the job is available on the queue, it is immediately consumed by the sender to process it.

When sending transactions, all the transactions that fails for some reason (example nonce too low) are added to an array and before setting the job as done, they are pushed again to the queue so they can be reprocessed later. After finishing with the job, the sender is ready to take the next job from the queue, which is probably the failed array of transactions. That's why re-tries happens too fast. When the sender finishes with the job, the new job with the failed tx is already there waiting to be consumed. 

 A couple of ideas we can apply to reduce logs are:
- Add an attribute to transactions that are reprocessed so we can reduce some logs for those cases and only log important information.
- Delay execution of reprocessed transactions pushed back to the queue. Rabbitmq does not support such feature in a native way, but one workaround for this is to push the job to a different queue with no consumers and after the specified `ttl` it will be catched by the [dead Letter Exchange](https://www.rabbitmq.com/dlx.html) and send it back to the queue that the sender is consuming. Example implementation https://blog.forma-pro.com/rabbitmq-retries-on-node-js-1f82c6afc1a1

What do you think @akolotov ?

**Comment by akolotov** [comment]
Thanks @patitonar for analysis.

I like the second approach but I am worrying about `ttl` value. What I would prefer is to have additional field for every job keeping `timeout` value for this particular job. It could allow change time frame between two attempts of the job. For example, the time between the first and the second attempts could be 1 sec, between 2nd and 3rd - 3 seconds, between 3rd and 4th - 5 seconds (just an example, exact values are negotiable). Do you think it is possible to achieve?

**Comment by patitonar** [comment]
Yes, I think it is possible to achieve. After some research I found that the best solution for this is to dynamically create new queues for each timeout defined on the jobs. After the last message is removed from these queues, the queue itself is also deleted. [Here is more information about this strategy](https://m.alphasights.com/exponential-backoff-with-rabbitmq-78386b9bec81). Timeout values for the retries attempts could be exponential

**Comment by akolotov** [comment]
Great! Looks like this is what we need.
